AY2425S2-CS2103T-F10-3/tp

docs/AboutUs.md

Update aboutus page for Jake

---

docs/DeveloperGuide.md

Edit target user profile, value proposition, and user stories
Fixes #37

Edit target user profile, value proposition, and user stories

---

src/main/java/seedu/address/logic/Messages.java
src/main/java/seedu/address/logic/commands/AddCommand.java
src/main/java/seedu/address/logic/commands/EditCommand.java
src/main/java/seedu/address/logic/parser/AddCommandParser.java
src/main/java/seedu/address/logic/parser/CliSyntax.java
src/main/java/seedu/address/logic/parser/ParserUtil.java
src/main/java/seedu/address/model/person/Person.java
src/main/java/seedu/address/model/person/Year.java
src/main/java/seedu/address/model/util/SampleDataUtil.java
src/main/java/seedu/address/storage/JsonAdaptedPerson.java
src/main/java/seedu/address/ui/PersonCard.java
src/main/resources/view/PersonListCard.fxml
src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json
src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
src/test/java/seedu/address/logic/LogicManagerTest.java
src/test/java/seedu/address/logic/commands/CommandTestUtil.java
src/test/java/seedu/address/logic/commands/EditPersonDescriptorTest.java
src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
src/test/java/seedu/address/model/person/PersonTest.java
src/test/java/seedu/address/model/person/YearTest.java
src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
src/test/java/seedu/address/testutil/PersonBuilder.java
src/test/java/seedu/address/testutil/PersonUtil.java
src/test/java/seedu/address/testutil/SampleDataUtilTest.java
src/test/java/seedu/address/testutil/TypicalPersons.java

Students can now add other people with an additional label: Year

Improve Add functionality by increment again

---

src/main/java/seedu/address/ui/HelpWindow.java
src/main/resources/view/HelpWindow.css
src/main/resources/view/HelpWindow.fxml

Improve the UI for the Help Window

---

src/main/java/seedu/address/model/person/Phone.java
src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
src/test/java/seedu/address/logic/parser/ParserUtilTest.java
src/test/java/seedu/address/model/person/NameContainsKeywordsPredicateTest.java
src/test/java/seedu/address/model/person/PhoneTest.java
src/test/java/seedu/address/testutil/TypicalPersons.java

Changed and added new test cases for new phone number restriction (now it must be at least 8 digits long instead of 3).
Fixes #77

Update add restrictions.

---

src/test/java/seedu/address/MainAppTest.java

Rewrite test cases for MainApp.java

---

src/main/java/seedu/address/commons/util/FileUtil.java
src/main/java/seedu/address/ui/UiManager.java
src/test/java/seedu/address/commons/util/FileUtilTest.java

Backup old data when corrupted data detected

---

docs/UserGuide.md

User Guide had some formatting and structure errors.

Fix errors in UserGuide.md

---

src/main/java/seedu/address/commons/util/FileUtil.java

Add assert for backupFile function in FileUtil.java

---

src/main/java/seedu/address/ui/HelpWindow.java

Added assert statements in HelpWindow.java
Fixes #89.

Add assert statements to HelpWindow.java

---

src/main/java/seedu/address/logic/commands/FindCommand.java
src/main/java/seedu/address/logic/parser/FindCommandParser.java
src/main/java/seedu/address/model/person/PersonContainsKeywordsPredicate.java
src/test/java/seedu/address/logic/commands/CommandTestUtil.java
src/test/java/seedu/address/logic/commands/FindCommandTest.java
src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
src/test/java/seedu/address/logic/parser/FindCommandParserTest.java
src/test/java/seedu/address/model/ModelManagerTest.java
src/test/java/seedu/address/model/person/PersonContainsKeywordsPredicateTest.java

Changed NameContainsKeywordPredicate to PersonContainsKeyWordPredicate ensures clarity.

Update naming conventions for find feature

---

src/main/java/seedu/address/ui/PersonCard.java
src/main/resources/view/PersonListCard.fxml

Enhance and improve on the add feature.
Fix #92

Add new labels and also improve Ui design

---

src/main/java/seedu/address/logic/commands/AddCommand.java

Add assert statements for AddCommand

---

docs/SettingUp.md
docs/diagrams/ArchitectureDiagram.puml
docs/diagrams/BetterModelClassDiagram.puml
src/main/java/seedu/address/commons/util/AppUtil.java
src/main/java/seedu/address/setup/AppParameters.java
src/main/java/seedu/address/setup/Main.java
src/main/java/seedu/address/setup/MainApp.java
src/main/java/seedu/address/ui/UiManager.java
src/main/java/seedu/address/ui/UiPart.java
src/test/java/seedu/address/AppParametersTest.java
src/test/java/seedu/address/MainAppTest.java
src/test/java/seedu/address/ui/UiPartTest.java

Draft of new updated UML diagrams

Branch jake updatedevguide1

---

build.gradle

Update build.gradle to fix bugs when running the application.

Update build.gradle to fix bugs

---

docs/diagrams/ArchitectureSequenceDiagram.puml

Include "setup" in UML diagram

---

docs/DeveloperGuide.md
docs/UserGuide.md
docs/diagrams/ArchitectureDiagram.puml
docs/diagrams/BackupOnCorruptSequenceDiagram.puml
docs/diagrams/style.puml

Fixes #116 
Developer Guide for this part is not complete. Will update it in next iteration.

Create new UML diagram for backup on corrupted data feature

---

src/main/java/seedu/address/logic/commands/DeleteCommand.java
src/main/java/seedu/address/ui/ConfirmDeleteWindow.java
src/main/resources/view/ConfirmDeleteWindow.css
src/main/resources/view/ConfirmDeleteWindow.fxml
src/test/java/seedu/address/logic/commands/DeleteCommandTest.java

Improve delete functionality where users now have to confirm deletion of their person of choice.
Fix #119

Branch jake increment del1

---

docs/UserGuide.md

Refine UserGuide for better formatting, as well as to facilitate changes due to update from Year to Major.
Fix #122

Update UserGuide.md and improve formatting

---

src/main/java/seedu/address/logic/parser/ParserUtil.java
src/main/java/seedu/address/model/tag/Priority.java
src/main/java/seedu/address/model/tag/Tag.java
src/main/java/seedu/address/model/util/SampleDataUtil.java
src/main/java/seedu/address/storage/JsonAdaptedTag.java
src/main/java/seedu/address/ui/PersonCard.java
src/main/resources/view/DarkTheme.css
src/test/data/JsonAddressBookStorageTest/invalidPersonAddressBook.json
src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json
src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
src/test/java/seedu/address/logic/parser/ParserUtilTest.java
src/test/java/seedu/address/model/person/PersonTest.java
src/test/java/seedu/address/model/tag/PriorityTest.java
src/test/java/seedu/address/model/tag/TagTest.java
src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
src/test/java/seedu/address/testutil/TypicalPersons.java
src/test/java/seedu/address/testutil/TypicalTags.java

Tags now have priority for users to classify their contacts.
Fix #142

Refine tag feature by including priority

---

docs/DeveloperGuide.md
docs/UserGuide.md
docs/diagrams/BackupOnCorruptSequenceDiagram.puml

Fix UML diagram for backup and update developerGuide

---

docs/UserGuide.md

Update UG for sort function

---

src/main/java/seedu/address/model/person/PersonContainsKeywordsPredicate.java

Users can find based on priority too.
Fix #143

Refine and enhance find command

---

docs/UserGuide.md

Fix incorrect YAML front matter in UserGuide.md

---

src/main/resources/view/HelpWindow.css
src/main/resources/view/HelpWindow.fxml

Reduced the size of the window.
Fixes #172

Update HelpWindow UI

---

docs/UserGuide.md

Update UG table of content and certain inconsistency in description

---

docs/UserGuide.md

Update UG with better example

---

docs/DeveloperGuide.md

Reverts AY2425S2-CS2103T-F10-3/tp#185

Revert "Update DeveloperGuide.md"

---

docs/UserGuide.md

Partially work on userguide to test formatting

Partially update userguide

---

docs/DeveloperGuide.md

Do not merge this PR yet. I will push small updates one by one.

Update incomplete part in DG

---

docs/UserGuide.md

Refine formatting for UserGuide.md

---

docs/UserGuide.md

Update icon and image size

---

docs/DeveloperGuide.md
docs/_markbind/layouts/default.md

Update Dev Guide to create ToC

Update Dev Guide

---

docs/_markbind/layouts/default.md

Restore default.md

---

docs/UserGuide.md

Refine formatting and elaboration

Refine formatting and elaboration for UserGuide.md

---

src/main/java/seedu/address/model/person/Phone.java
src/test/java/seedu/address/model/person/PhoneTest.java

Updated the phone number length to ensure that it is in between 4 to 17 digits long.
Fixes #219  and #203

Update Phone Number Length

---

src/main/java/seedu/address/model/person/Email.java
src/test/java/seedu/address/model/person/EmailTest.java

Update email to ensure that the characters does not exceed 100 characters.
Fixes #206
Fixes #208 
Fixes #211 
Fixes #213

Branch nic updateemaillength 1

---

src/main/java/seedu/address/model/person/Name.java
src/main/resources/view/PersonListCard.fxml
src/test/java/seedu/address/model/person/NameTest.java

Update Name limits

---

src/main/java/seedu/address/model/person/Name.java
src/test/java/seedu/address/model/person/PersonTest.java

Fix spacing issues for names , fix #223

Branch jake v1.6fixbug1

---

src/main/java/seedu/address/logic/parser/AddCommandParser.java
src/main/java/seedu/address/logic/parser/EditCommandParser.java
src/main/java/seedu/address/logic/parser/ParserUtil.java
src/main/java/seedu/address/model/person/Major.java

Fix buggy warnings

---

src/main/java/seedu/address/model/person/Person.java
src/test/java/seedu/address/model/person/PersonTest.java

Update Person.java and PersonTest.java
Fixes #228 
Fixes #223 
Fixes #226

Update Person and PersonTest.java

---

src/main/java/seedu/address/logic/commands/DeleteCommand.java
src/main/java/seedu/address/logic/parser/DeleteCommandParser.java

Delete command was buggy, fixed those bugs already
Fix #217

Fix bugs for delete command

---

docs/DeveloperGuide.md
docs/diagrams/BackupOnCorruptSequenceDiagram.puml
src/main/java/seedu/address/commons/util/FileUtil.java
src/main/java/seedu/address/ui/UiManager.java
src/test/java/seedu/address/commons/util/FileUtilTest.java

Fix corrupted data file not deleted after backup

---

src/main/java/seedu/address/logic/parser/ParserUtil.java
src/main/java/seedu/address/model/tag/Priority.java
src/test/java/seedu/address/model/tag/PriorityTest.java

Fixes #230 
Please test by trying to recreate the bug.

Fix app crashes if priority is not valid in json file 

---

src/main/java/seedu/address/logic/parser/AddCommandParser.java
src/main/java/seedu/address/logic/parser/CliSyntax.java
src/test/java/seedu/address/logic/parser/AddCommandParserTest.java

Update specific missing parameter error message

---

src/main/java/seedu/address/logic/parser/AddressBookParser.java
src/test/java/seedu/address/logic/parser/AddressBookParserTest.java

Fix commands are case sensitive

---

src/main/java/seedu/address/logic/parser/DeleteCommandParser.java
src/main/java/seedu/address/logic/parser/ParserUtil.java
src/test/java/seedu/address/logic/parser/DeleteCommandParserTest.java

Fix incorrect status message for delete command

---

docs/UserGuide.md

Update UG to fix these issues.
Fix #207 
Fix #177

Improve UG designs and explanations

---

docs/DeveloperGuide.md
docs/diagrams/AddCommand.puml

Add workflow of add command in developerGuide

---

docs/DeveloperGuide.md

Include appendix for DG on planned enhancements and effort.
Fix #165

Include appendix for DG
